server.address=0.0.0.0
spring.application.name=acme-task

spring.datasource.url=jdbc:postgresql://localhost:5432/acme
spring.datasource.username=acme
spring.datasource.password=acme1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db.changelog.yaml
spring.liquibase.contexts=,default
logging.level.com.acme=DEBUG

spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=8